/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ImageEditorPackage;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author Jaryna
 */
public class imagePanel extends javax.swing.JPanel {

    /**
     * Creates new form imagePanel
     */
    private ArrayList<File> imagesSelected = new ArrayList<File>();
    
    public imagePanel() {
        initComponents();
    }

    public ArrayList<File> geimagesSelectedList(){
        return imagesSelected;
    }
    
    imagePanel(Image image , File img) {
        this.setSize(250, 250);
        Image tmp =null;
        tmp = image.getScaledInstance(250, 250 , Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(tmp);
        JLabel picLabel = new JLabel(icon);
        JCheckBox checkbox = new JCheckBox();
        checkbox.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                imagesSelected.add(img);
            }
        });
        checkbox.setVisible(true);
        
        picLabel.add(checkbox);
        
        picLabel.setSize(this.getSize());
        this.add(picLabel);
        this.add(checkbox);
        //this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
