/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ImageEditorPackage;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import static java.lang.Math.random;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Jaryna
 */
public class ThirdPanelOperation extends javax.swing.JPanel {

    /**
     * Creates new form ThirdPanelOperation
     */
    //array for Generic Filter of files that should be in  our chosen directory
    String[] array = {".jpg",".png", ".jpeg"," .tiff",".tif"," .bmp" ,".JPG" };
    
    private   mainFrame parentFrame = (mainFrame) this.getParent();
    public ArrayList<ArrayList<imagePanel>> selectedDirectories = new  ArrayList<>();
    public ArrayList<imagePanel> resultArray  = new ArrayList<>();
    
    public void setParentFrame(mainFrame frame) {
        parentFrame = frame;
    }
    
    ButtonGroup group  = new ButtonGroup();
    ButtonGroup group_cutout  = new ButtonGroup();
    ButtonGroup group_format  = new ButtonGroup();
    
    String selectedButton = "AND";
    
    String selectedSizeType = "ErlargeSmaller";
    //0 - ErlargeSmaller 1 - Shrink Bigger 2- Center(put in the middle) 3 - CutOut
    public int sizeType = 0 ; 
    
    public ThirdPanelOperation() {
        initComponents();
        group.add(jRadioButton1);
        group.add(jRadioButton2);
        group.add(jRadioButton3);
        
        group_cutout.add(jRadioButton4);
        group_cutout.add(jRadioButton5);  
        
        group_format.add(formatJPEG);
        group_format.add(formatJPG);
        group_format.add(formatPNG);
        group_format.add(formatTIFF);
        group_format.add(formatBMP);
        
    
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelForOperations = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        buttonMergeSelectedPictures = new javax.swing.JButton();
        buttonMergeDirectories = new javax.swing.JButton();
        buttonClearResults = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        box1 = new javax.swing.JCheckBox();
        box2 = new javax.swing.JCheckBox();
        box3 = new javax.swing.JCheckBox();
        box5 = new javax.swing.JCheckBox();
        box4 = new javax.swing.JCheckBox();
        buttonCutout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        textStripe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonSaveSelected = new javax.swing.JButton();
        buttonSaveAll = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        formatPNG = new javax.swing.JRadioButton();
        formatBMP = new javax.swing.JRadioButton();
        formatTIFF = new javax.swing.JRadioButton();
        formatJPEG = new javax.swing.JRadioButton();
        formatJPG = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 102, 0));
        setMaximumSize(new java.awt.Dimension(2147483647, 200));
        setPreferredSize(new java.awt.Dimension(300, 353));

        panelForOperations.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N
        panelForOperations.setPreferredSize(new java.awt.Dimension(300, 535));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Merge", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 10))); // NOI18N

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("AND");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("OR");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("XOR");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Erlarge smaller", "Shrink bigger", "Center", "Center and cut" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1)
                .addContainerGap())
        );

        buttonMergeSelectedPictures.setText("Merge Pictures");
        buttonMergeSelectedPictures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMergeSelectedPicturesActionPerformed(evt);
            }
        });

        buttonMergeDirectories.setText("Merge Directories");
        buttonMergeDirectories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMergeDirectoriesActionPerformed(evt);
            }
        });

        buttonClearResults.setText("Clear Results");
        buttonClearResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearResultsActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Directories To merge", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 10))); // NOI18N

        box1.setText("Directory 1");
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        box2.setText("Directory 2");
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });

        box3.setText("Directory 3");
        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });

        box5.setText("Directory 5");
        box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5ActionPerformed(evt);
            }
        });

        box4.setText("Directory 4");
        box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box1)
                    .addComponent(box2)
                    .addComponent(box3)
                    .addComponent(box4)
                    .addComponent(box5))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(box1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box5))
        );

        buttonCutout.setText("Cutout pictures");
        buttonCutout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCutoutActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cutout options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 10))); // NOI18N

        jRadioButton4.setSelected(true);
        jRadioButton4.setText("Vertical Cutout");

        jRadioButton5.setText("Horizontal Cutout");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        textStripe.setText("1");
        textStripe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStripeActionPerformed(evt);
            }
        });

        jLabel1.setText("Num of Stripes :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(textStripe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(textStripe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        buttonSaveSelected.setText("Save Selected");
        buttonSaveSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveSelectedActionPerformed(evt);
            }
        });

        buttonSaveAll.setText("Save All");
        buttonSaveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveAllActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Save as", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 10))); // NOI18N

        formatPNG.setText("PNG");
        formatPNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatPNGActionPerformed(evt);
            }
        });

        formatBMP.setText("BMP");
        formatBMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatBMPActionPerformed(evt);
            }
        });

        formatTIFF.setText("TIFF");
        formatTIFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatTIFFActionPerformed(evt);
            }
        });

        formatJPEG.setText("JPEG");
        formatJPEG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatJPEGActionPerformed(evt);
            }
        });

        formatJPG.setText("JPG");
        formatJPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatJPGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formatPNG)
            .addComponent(formatBMP)
            .addComponent(formatTIFF)
            .addComponent(formatJPEG)
            .addComponent(formatJPG)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formatPNG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formatBMP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formatTIFF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formatJPEG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formatJPG)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelForOperationsLayout = new javax.swing.GroupLayout(panelForOperations);
        panelForOperations.setLayout(panelForOperationsLayout);
        panelForOperationsLayout.setHorizontalGroup(
            panelForOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelForOperationsLayout.createSequentialGroup()
                .addGroup(panelForOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelForOperationsLayout.createSequentialGroup()
                        .addGroup(panelForOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonClearResults, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSaveSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelForOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonSaveAll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCutout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                            .addComponent(buttonMergeSelectedPictures, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(buttonMergeDirectories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        panelForOperationsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonMergeDirectories, buttonMergeSelectedPictures});

        panelForOperationsLayout.setVerticalGroup(
            panelForOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelForOperationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelForOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelForOperationsLayout.createSequentialGroup()
                        .addComponent(buttonCutout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMergeDirectories)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonMergeSelectedPictures)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSaveAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSaveSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonClearResults)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelForOperationsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonCutout, buttonMergeDirectories, buttonMergeSelectedPictures});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelForOperations, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelForOperations, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMergeSelectedPicturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMergeSelectedPicturesActionPerformed
        ArrayList<imagePanel> currentSelectedImagePanels = new ArrayList<>();

        try{
            currentSelectedImagePanels = parentFrame.getImageEditor().getCurrentPanelSetOfImages();
        }
        catch(Exception exc){}
        Merging Test = new Merging();
        
        //Getting type of selected choice how to merge (OR , XOR , AND)
        int type = 0 ;
        
        if(null != selectedButton)switch (selectedButton) {
            case "AND":
                type = 0;
                break;
            case "OR":
                type = 1;
                break;
            case "XOR":
                type = 2;
                break;
        }
        
        //Getting selected images  and putting them into ArrayList<File> inside Test(class Merging instance)
        for(imagePanel imgPn : currentSelectedImagePanels ){
            if(imgPn.selected == true)
                Test.imagesSelected.add(imgPn.fileOfImage);
        }
        
        if(Test.imagesSelected.isEmpty() == true){
            //custom title, error icon
            JOptionPane.showMessageDialog(parentFrame,"Choose image before you merge and click directory button on the top of the Image Editor to update you choice","" ,JOptionPane.ERROR_MESSAGE);
        }
        else{
        //Merging operation in action
            try{
                Test.merge(type);
            }
            catch(Exception e){}
        }
        
        fullFillPanelwithOneMergedImage(parentFrame.getImageEditor().getPanelForResult() , Test.result_image  , Test.result);
    }//GEN-LAST:event_buttonMergeSelectedPicturesActionPerformed

    
   
    
    JPanel jpn1child = new JPanel();
    JScrollPane scrollpane = new JScrollPane(jpn1child);
    
    public void fullFillPanelwithOneMergedImage(JPanel JpnN , Image image , BufferedImage buff ){
        GenericExtFilter filter = new GenericExtFilter(array);
        //JpnN.removeAll();
        
        JpnN.setBackground(java.awt.Color.ORANGE);
        
        jpn1child.setLayout(new GridLayout(0,2));
        
        if(image!=null){
            imagePanel jp = new imagePanel(image  , null);
            jp.setSize(300,300);
            jp.buffimage = buff;
            jpn1child.add(jp);
            jp.setVisible(true);
            resultArray.add(jp);
        }
        
        scrollpane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollpane.setBounds(30, 50, parentFrame.getImageEditor().getPanelForResult().getParent().getWidth(), 20000);
        JpnN.setLayout(new BorderLayout());
        JpnN.add(scrollpane , BorderLayout.CENTER);
        JpnN.repaint();
        JpnN.revalidate();
        parentFrame.getImageEditor().getPanelForIcons().updateUI();
    }
    
    public void fullFillPanelwithDirMerged(JPanel JpnN ,ArrayList<Image> images , ArrayList<BufferedImage> buff){
        GenericExtFilter filter = new GenericExtFilter(array);
        
        
        JpnN.setBackground(java.awt.Color.pink);
        
        jpn1child.setLayout(new GridLayout(0,2));
        int i = 0;
        if(images!=null){
            for(Image image : images){
                
                imagePanel jp = new imagePanel(image  , null);
                jp.setSize(300,300);
                jpn1child.add(jp);
                jp.setVisible(true);
                
                jp.buffimage = buff.get(i);
                i++;
            }
        }
        
        scrollpane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollpane.setBounds(30, 50, parentFrame.getImageEditor().getPanelForResult().getParent().getWidth(), 20000);
        JpnN.setLayout(new BorderLayout());
        JpnN.add(scrollpane , BorderLayout.CENTER);
        JpnN.repaint();
        JpnN.revalidate();
        parentFrame.getImageEditor().getPanelForIcons().updateUI();
    }
    
 public void fullFillPanelwithCutout(JPanel JpnN ,Image image , BufferedImage buff ){
        GenericExtFilter filter = new GenericExtFilter(array);
        
        
        JpnN.setBackground(java.awt.Color.pink);
        
        jpn1child.setLayout(new GridLayout(0,2));
        
        if(image!=null){
            imagePanel jp = new imagePanel(image  , null);
            jp.setSize(300,300);
            jpn1child.add(jp);
            jp.setVisible(true);
            jp.buffimage = buff;
         }
        
        scrollpane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollpane.setBounds(30, 50, parentFrame.getImageEditor().getPanelForResult().getParent().getWidth(), 20000);
        JpnN.setLayout(new BorderLayout());
        JpnN.add(scrollpane , BorderLayout.CENTER);
        JpnN.repaint();
        JpnN.revalidate();
        parentFrame.getImageEditor().getPanelForIcons().updateUI();
    }
    
    
                               

    
    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       //0 - ErlargeSmaller 1 - Shrink Bigger 2- Center(put in the middle) 3 - CutOut
        selectedSizeType =jComboBox1.getSelectedItem().toString();
        switch (selectedSizeType) {
            case "Center":
                sizeType=2;
                break;
            case "Enlarge smaller":
                sizeType=0;
                break;
            case "Shrink bigger":     
                sizeType=1;
                break;
            case "Center and cut":
                sizeType=3;
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        selectedButton = "AND";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        selectedButton = "OR";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        selectedButton = "XOR";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void buttonMergeDirectoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMergeDirectoriesActionPerformed

        ArrayList<ArrayList<imagePanel>> currentDirectoriesToMerge = new ArrayList<>();
        try{
            currentDirectoriesToMerge = parentFrame.getOperationsPanel().selectedDirectories;
        }
        catch(Exception exc){}
        Merging_Directories Test = new Merging_Directories();
        
        //Getting type of selected choice how to merge (OR , XOR , AND)
        int type = 0 ;
        
        //select type how to merge
        if(null != selectedButton)switch (selectedButton) {
            case "AND":
                type = 0;
                break;
            case "OR":
                type = 1;
                break;
            case "XOR":
                type = 2;
                break;
        }
        
        //Getting selected images  and putting them into ArrayList<File> inside Test(class MergingDir instance)
        for(ArrayList<imagePanel> imgPanCont : currentDirectoriesToMerge  ){
            ArrayList<File> temp = new ArrayList();
                for(imagePanel imgPn :imgPanCont ){
                    temp.add(imgPn.fileOfImage);
             }
          Test.foldersWithImages.add(temp);
        }
        
        if(Test.foldersWithImages.isEmpty() == true){
            //custom title, error icon
            JOptionPane.showMessageDialog(parentFrame,"Choose image/directory before you merge","" ,JOptionPane.ERROR_MESSAGE);
        }
        else{
        //Merging operation in action
            try{
                Test.mergeDir(type);
            }
            catch(Exception e){}
        }
        
        fullFillPanelwithDirMerged(parentFrame.getImageEditor().getPanelForResult() , Test.resultDir , Test.resultDirr );                        

    }//GEN-LAST:event_buttonMergeDirectoriesActionPerformed

    private void buttonClearResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearResultsActionPerformed
        parentFrame.getImageEditor().getPanelForResult().removeAll();
        jpn1child.removeAll();
        parentFrame.getImageEditor().getPanelForResult().updateUI();
        resultArray.clear();
    }//GEN-LAST:event_buttonClearResultsActionPerformed

    boolean selectedDir1 = false;
    boolean selectedDir2 = false;
    boolean selectedDir3 = false;
    boolean selectedDir4 = false;
    boolean selectedDir5 = false;
    
    public void actionForComboBox(boolean selected , ArrayList<imagePanel> imgesFromPanel){
     if(selected==false){
            selected = true;
            //ArrayList<ArrayList<imagePanel>>
            ArrayList<imagePanel> currentForConecting = new ArrayList();
            currentForConecting.addAll(imgesFromPanel);
            selectedDirectories.add(currentForConecting);
        }
        else if(selected==true){
            selected = false;
            selectedDirectories.removeAll(imgesFromPanel);
        }
    }
    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        actionForComboBox(selectedDir1 , parentFrame.getImageBrowser().getImagePanel1());
    }//GEN-LAST:event_box1ActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
         actionForComboBox(selectedDir2 , parentFrame.getImageBrowser().getImagePanel2());
    }//GEN-LAST:event_box2ActionPerformed

    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
        actionForComboBox(selectedDir3 , parentFrame.getImageBrowser().getImagePanel3());
    }//GEN-LAST:event_box3ActionPerformed

    private void box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4ActionPerformed
       actionForComboBox(selectedDir4 , parentFrame.getImageBrowser().getImagePanel4());
    }//GEN-LAST:event_box4ActionPerformed

    private void box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5ActionPerformed
        actionForComboBox(selectedDir5 , parentFrame.getImageBrowser().getImagePanel5());
    }//GEN-LAST:event_box5ActionPerformed

    private void buttonCutoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCutoutActionPerformed
       ArrayList<imagePanel> currentSelectedImagePanels = new ArrayList<>();
       number  = Integer.parseInt(textStripe.getText());
        try{
            currentSelectedImagePanels = parentFrame.getImageEditor().getCurrentPanelSetOfImages();
        }
        catch(Exception exc){}
        Cutout Test = new Cutout();
        int type = 0 ;
        //Getting type of selected choice how to merge (OR , XOR , AND)
        if( jRadioButton5.isSelected()){
            type = 1;
        }
        
     
        
        //Getting selected images  and putting them into ArrayList<File> inside Test(class Merging instance)
        for(imagePanel imgPn : currentSelectedImagePanels ){
            if(imgPn.selected == true)
                Test.imagesSelected.add(imgPn.fileOfImage);
        }
        
        if(Test.imagesSelected.isEmpty() == true){
            //custom title, error icon
            JOptionPane.showMessageDialog(parentFrame,"Choose image before you make a cutput and click directory button on the top of the Image Editor to update you choice","" ,JOptionPane.ERROR_MESSAGE);
        }
        else{
        //Merging operation in action
            try{
                Test.cut(number,type);
            }
            catch(Exception e){}
        }
        
        fullFillPanelwithCutout(parentFrame.getImageEditor().getPanelForResult() , Test.result_image  , Test.result);
        
    }//GEN-LAST:event_buttonCutoutActionPerformed

    int number  = 1; 
    private void textStripeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStripeActionPerformed
       
       
    }//GEN-LAST:event_textStripeActionPerformed

    private void buttonSaveSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveSelectedActionPerformed
       JFileChooser jFile = new JFileChooser();
        jFile.setDialogTitle("Save file ...");
        jFile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValue  = jFile.showSaveDialog(parentFrame);
        //Path pth = jFile.getSelectedFile().toPath();
        Path pth = jFile.getSelectedFile().toPath();
        
        File file = jFile.getSelectedFile();
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
        for(imagePanel imgpan : resultArray){
                if(imgpan.selected==true){
                    Random ran = new Random();
                    Integer n  = ran.nextInt((30 - 2) + 1) + 2;
                    String filename = "Image1" + n.toString();
               try {
                    ImageIO.write( imgpan.buffimage,"bmp" ,new File(pth + "\\" + filename+extention));
                } catch (IOException ex) {
                    ex.printStackTrace();
                }

               }
           }
        }
    }//GEN-LAST:event_buttonSaveSelectedActionPerformed

    private void buttonSaveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveAllActionPerformed
        
        JFileChooser jFile = new JFileChooser();
        jFile.setDialogTitle("Save file ...");
        jFile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValue  = jFile.showSaveDialog(parentFrame);
        //Path pth = jFile.getSelectedFile().toPath();
        Path pth = jFile.getSelectedFile().toPath();
        
        File file = jFile.getSelectedFile();
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
        for(imagePanel imgpan : resultArray){
            Random ran = new Random();
            Integer n  = ran.nextInt((30 - 2) + 1) + 2;
            String filename = "Image1" + n.toString();
           try {
                ImageIO.write( imgpan.buffimage,"bmp" ,new File(pth + "\\" + filename+extention));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            
            }
        }
            
  
    }//GEN-LAST:event_buttonSaveAllActionPerformed
    
    private String extention = ".jpg";    
    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void formatJPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatJPGActionPerformed
        extention = ".jpg";
    }//GEN-LAST:event_formatJPGActionPerformed

    private void formatPNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatPNGActionPerformed
         extention = ".png";
    }//GEN-LAST:event_formatPNGActionPerformed

    private void formatBMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatBMPActionPerformed
         extention = ".bmp";
    }//GEN-LAST:event_formatBMPActionPerformed

    private void formatTIFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatTIFFActionPerformed
         extention = ".tiff";
    }//GEN-LAST:event_formatTIFFActionPerformed

    private void formatJPEGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatJPEGActionPerformed
         extention = ".jpeg";
    }//GEN-LAST:event_formatJPEGActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox box1;
    private javax.swing.JCheckBox box2;
    private javax.swing.JCheckBox box3;
    private javax.swing.JCheckBox box4;
    private javax.swing.JCheckBox box5;
    private javax.swing.JButton buttonClearResults;
    private javax.swing.JButton buttonCutout;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonMergeDirectories;
    private javax.swing.JButton buttonMergeSelectedPictures;
    private javax.swing.JButton buttonSaveAll;
    private javax.swing.JButton buttonSaveSelected;
    private javax.swing.JRadioButton formatBMP;
    private javax.swing.JRadioButton formatJPEG;
    private javax.swing.JRadioButton formatJPG;
    private javax.swing.JRadioButton formatPNG;
    private javax.swing.JRadioButton formatTIFF;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JPanel panelForOperations;
    private javax.swing.JTextField textStripe;
    // End of variables declaration//GEN-END:variables
}
